/**
 * @file ConsoleStyle.h
 *
 * @author  gilnaa
 * @since   29/04/2016
 */

#ifndef NLOG_CONSOLESTYLE_H
#define NLOG_CONSOLESTYLE_H

#define NLOG_CONSOLE_ESCAPE(id) "\x1b[" #id "m"
#define NLOG_CONSOLE_RESET                  NLOG_CONSOLE_ESCAPE(0)

#define NLOG_CONSOLE_BOLD                   NLOG_CONSOLE_ESCAPE(1)
#define NLOG_CONSOLE_HALFBRIGHT             NLOG_CONSOLE_ESCAPE(2)

#define NLOG_CONSOLE_UNDERSCORE             NLOG_CONSOLE_ESCAPE(4)
#define NLOG_CONSOLE_UNDERSCORE_OFF         NLOG_CONSOLE_ESCAPE(24)

#define NLOG_CONSOLE_BLINK                  NLOG_CONSOLE_ESCAPE(5)
#define NLOG_CONSOLE_BLINK_OFF              NLOG_CONSOLE_ESCAPE(25)

#define NLOG_CONSOLE_REVERSE_VIDEO          NLOG_CONSOLE_ESCAPE(7)
#define NLOG_CONSOLE_REVERSE_VIDEO_OFF      NLOG_CONSOLE_ESCAPE(27)
/**
 * Foreground (text) colors.
 */
#define NLOG_CONSOLE_FOREGROUND_BLACK       NLOG_CONSOLE_ESCAPE(30)
#define NLOG_CONSOLE_FOREGROUND_RED         NLOG_CONSOLE_ESCAPE(31)
#define NLOG_CONSOLE_FOREGROUND_GREEN       NLOG_CONSOLE_ESCAPE(32)
#define NLOG_CONSOLE_FOREGROUND_BROWN       NLOG_CONSOLE_ESCAPE(33)
#define NLOG_CONSOLE_FOREGROUND_BLUE        NLOG_CONSOLE_ESCAPE(34)
#define NLOG_CONSOLE_FOREGROUND_MAGENTA     NLOG_CONSOLE_ESCAPE(35)
#define NLOG_CONSOLE_FOREGROUND_CYAN        NLOG_CONSOLE_ESCAPE(36)
#define NLOG_CONSOLE_FOREGROUND_WHITE       NLOG_CONSOLE_ESCAPE(37)
/**
 * Background colors.
 */
#define NLOG_CONSOLE_BACKGROUND_BLACK       NLOG_CONSOLE_ESCAPE(40)
#define NLOG_CONSOLE_BACKGROUND_RED         NLOG_CONSOLE_ESCAPE(41)
#define NLOG_CONSOLE_BACKGROUND_GREEN       NLOG_CONSOLE_ESCAPE(42)
#define NLOG_CONSOLE_BACKGROUND_BROWN       NLOG_CONSOLE_ESCAPE(43)
#define NLOG_CONSOLE_BACKGROUND_BLUE        NLOG_CONSOLE_ESCAPE(44)
#define NLOG_CONSOLE_BACKGROUND_MAGENTA     NLOG_CONSOLE_ESCAPE(45)
#define NLOG_CONSOLE_BACKGROUND_CYAN        NLOG_CONSOLE_ESCAPE(46)
#define NLOG_CONSOLE_BACKGROUND_WHITE       NLOG_CONSOLE_ESCAPE(47)
#define NLOG_CONSOLE_BACKGROUND_DEFAULT     NLOG_CONSOLE_ESCAPE(49)

#endif //NLOG_CONSOLESTYLE_H
